
+ Contract Pool (Most derived contract)
  - From ERC20
    - DOMAIN_SEPARATOR() (public)
    - _approve(address,address,uint256) (internal)
    - _burn(address,uint256) (internal)
    - _decreaseAllowance(address,address,uint256) (internal)
    - _mint(address,uint256) (internal)
    - _transfer(address,address,uint256) (internal)
    - approve(address,uint256) (public)
    - constructor(string,string,uint8) (public)
    - decreaseAllowance(address,uint256) (public)
    - increaseAllowance(address,uint256) (public)
    - permit(address,address,uint256,uint256,uint8,bytes32,bytes32) (public)
  - From IERC20
    - PERMIT_TYPEHASH() (external)
    - allowance(address,address) (external)
    - balanceOf(address) (external)
    - decimals() (external)
    - name() (external)
    - nonces(address) (external)
    - symbol() (external)
    - totalSupply() (external)
  - From IPool
    - manager() (external)
  - From IERC4626
    - asset() (external)
  - From Pool
    - _burn(uint256,uint256,address,address,address) (internal)
    - _divRoundUp(uint256,uint256) (internal)
    - _mint(uint256,uint256,address,address) (internal)
    - _requestRedeem(uint256) (internal)
    - balanceOfAssets(address) (external)
    - constructor(address,address,address,uint256,string,string) (public)
    - convertToAssets(uint256) (public)
    - convertToExitShares(uint256) (public)
    - convertToShares(uint256) (public)
    - deposit(uint256,address) (external)
    - depositWithPermit(uint256,address,uint256,uint8,bytes32,bytes32) (external)
    - maxDeposit(address) (external)
    - maxMint(address) (external)
    - maxRedeem(address) (external)
    - maxWithdraw(address) (external)
    - mint(uint256,address) (external)
    - mintWithPermit(uint256,address,uint256,uint256,uint8,bytes32,bytes32) (external)
    - previewDeposit(uint256) (public)
    - previewMint(uint256) (public)
    - previewRedeem(uint256) (external)
    - previewWithdraw(uint256) (external)
    - redeem(uint256,address,address) (external)
    - removeShares(uint256) (external)
    - requestRedeem(uint256) (external)
    - requestWithdraw(uint256) (external)
    - totalAssets() (public)
    - transfer(address,uint256) (public)
    - transferFrom(address,address,uint256) (public)
    - unrealizedLosses() (public)
    - withdraw(uint256,address,address) (external)

+ Contract IERC4626
  - From IERC20
    - DOMAIN_SEPARATOR() (external)
    - PERMIT_TYPEHASH() (external)
    - allowance(address,address) (external)
    - approve(address,uint256) (external)
    - balanceOf(address) (external)
    - decimals() (external)
    - decreaseAllowance(address,uint256) (external)
    - increaseAllowance(address,uint256) (external)
    - name() (external)
    - nonces(address) (external)
    - permit(address,address,uint256,uint256,uint8,bytes32,bytes32) (external)
    - symbol() (external)
    - totalSupply() (external)
    - transfer(address,uint256) (external)
    - transferFrom(address,address,uint256) (external)
  - From IERC4626
    - asset() (external)
    - convertToAssets(uint256) (external)
    - convertToShares(uint256) (external)
    - deposit(uint256,address) (external)
    - maxDeposit(address) (external)
    - maxMint(address) (external)
    - maxRedeem(address) (external)
    - maxWithdraw(address) (external)
    - mint(uint256,address) (external)
    - previewDeposit(uint256) (external)
    - previewMint(uint256) (external)
    - previewRedeem(uint256) (external)
    - previewWithdraw(uint256) (external)
    - redeem(uint256,address,address) (external)
    - totalAssets() (external)
    - withdraw(uint256,address,address) (external)

+ Contract IPool
  - From IERC4626
    - asset() (external)
    - convertToAssets(uint256) (external)
    - convertToShares(uint256) (external)
    - deposit(uint256,address) (external)
    - maxDeposit(address) (external)
    - maxMint(address) (external)
    - maxRedeem(address) (external)
    - maxWithdraw(address) (external)
    - mint(uint256,address) (external)
    - previewDeposit(uint256) (external)
    - previewMint(uint256) (external)
    - previewRedeem(uint256) (external)
    - previewWithdraw(uint256) (external)
    - redeem(uint256,address,address) (external)
    - totalAssets() (external)
    - withdraw(uint256,address,address) (external)
  - From IERC20
    - DOMAIN_SEPARATOR() (external)
    - PERMIT_TYPEHASH() (external)
    - allowance(address,address) (external)
    - approve(address,uint256) (external)
    - balanceOf(address) (external)
    - decimals() (external)
    - decreaseAllowance(address,uint256) (external)
    - increaseAllowance(address,uint256) (external)
    - name() (external)
    - nonces(address) (external)
    - permit(address,address,uint256,uint256,uint8,bytes32,bytes32) (external)
    - symbol() (external)
    - totalSupply() (external)
    - transfer(address,uint256) (external)
    - transferFrom(address,address,uint256) (external)
  - From IPool
    - balanceOfAssets(address) (external)
    - convertToExitShares(uint256) (external)
    - depositWithPermit(uint256,address,uint256,uint8,bytes32,bytes32) (external)
    - manager() (external)
    - mintWithPermit(uint256,address,uint256,uint256,uint8,bytes32,bytes32) (external)
    - removeShares(uint256) (external)
    - requestRedeem(uint256) (external)
    - requestWithdraw(uint256) (external)
    - unrealizedLosses() (external)

+ Contract IERC20Like
  - From IERC20Like
    - balanceOf(address) (external)
    - decimals() (external)
    - totalSupply() (external)

+ Contract ILoanManagerLike (Most derived contract)
  - From ILoanManagerLike
    - acceptNewTerms(address,address,uint256,bytes[]) (external)
    - assetsUnderManagement() (external)
    - claim(address,bool) (external)
    - finishCollateralLiquidation(address) (external)
    - fund(address) (external)
    - removeDefaultWarning(address,bool) (external)
    - triggerDefault(address) (external)
    - triggerDefaultWarning(address,bool) (external)
    - unrealizedLosses() (external)

+ Contract ILoanManagerInitializerLike (Most derived contract)
  - From ILoanManagerInitializerLike
    - decodeArguments(bytes) (external)
    - encodeArguments(address) (external)

+ Contract ILiquidatorLike (Most derived contract)
  - From ILiquidatorLike
    - liquidatePortion(uint256,uint256,bytes) (external)
    - pullFunds(address,address,uint256) (external)

+ Contract ILoanV3Like (Most derived contract)
  - From ILoanV3Like
    - getNextPaymentBreakdown() (external)

+ Contract ILoanLike (Most derived contract)
  - From ILoanLike
    - acceptLender() (external)
    - acceptNewTerms(address,uint256,bytes[]) (external)
    - batchClaimFunds(uint256[],address[]) (external)
    - borrower() (external)
    - claimFunds(uint256,address) (external)
    - collateral() (external)
    - collateralAsset() (external)
    - feeManager() (external)
    - fundLoan(address) (external)
    - fundsAsset() (external)
    - getClosingPaymentBreakdown() (external)
    - getNextPaymentBreakdown() (external)
    - getNextPaymentDetailedBreakdown() (external)
    - gracePeriod() (external)
    - interestRate() (external)
    - isInDefaultWarning() (external)
    - lateFeeRate() (external)
    - nextPaymentDueDate() (external)
    - paymentInterval() (external)
    - paymentsRemaining() (external)
    - prewarningPaymentDueDate() (external)
    - principal() (external)
    - principalRequested() (external)
    - refinanceInterest() (external)
    - removeDefaultWarning() (external)
    - repossess(address) (external)
    - setPendingLender(address) (external)
    - triggerDefaultWarning() (external)

+ Contract IMapleGlobalsLike (Most derived contract)
  - From IMapleGlobalsLike
    - getLatestPrice(address) (external)
    - governor() (external)
    - isBorrower(address) (external)
    - isFactory(bytes32,address) (external)
    - isPoolAsset(address) (external)
    - isPoolDelegate(address) (external)
    - isPoolDeployer(address) (external)
    - isValidScheduledCall(address,address,bytes32,bytes) (external)
    - mapleTreasury() (external)
    - maxCoverLiquidationPercent(address) (external)
    - migrationAdmin() (external)
    - minCoverAmount(address) (external)
    - ownedPoolManager(address) (external)
    - platformManagementFeeRate(address) (external)
    - protocolPaused() (external)
    - transferOwnedPoolManager(address,address) (external)
    - unscheduleCall(address,bytes32,bytes) (external)

+ Contract IMapleLoanFeeManagerLike (Most derived contract)
  - From IMapleLoanFeeManagerLike
    - platformServiceFee(address) (external)

+ Contract IMapleProxyFactoryLike (Upgradeable Proxy) (Most derived contract)
  - From IMapleProxyFactoryLike
    - mapleGlobals() (external)

+ Contract IPoolDelegateCoverLike (Most derived contract)
  - From IPoolDelegateCoverLike
    - moveFunds(uint256,address) (external)

+ Contract IPoolLike (Most derived contract)
  - From IERC20Like
    - balanceOf(address) (external)
    - decimals() (external)
    - totalSupply() (external)
  - From IPoolLike
    - asset() (external)
    - convertToAssets(uint256) (external)
    - convertToExitShares(uint256) (external)
    - deposit(uint256,address) (external)
    - manager() (external)
    - previewMint(uint256) (external)
    - processExit(uint256,uint256,address,address) (external)
    - redeem(uint256,address,address) (external)

+ Contract IPoolManagerLike (Most derived contract)
  - From IPoolManagerLike
    - addLoanManager(address) (external)
    - canCall(bytes32,address,bytes) (external)
    - claim(address) (external)
    - convertToExitShares(uint256) (external)
    - delegateManagementFeeRate() (external)
    - fund(uint256,address,address) (external)
    - getEscrowParams(address,uint256) (external)
    - globals() (external)
    - hasSufficientCover() (external)
    - loanManager() (external)
    - maxDeposit(address) (external)
    - maxMint(address) (external)
    - maxRedeem(address) (external)
    - maxWithdraw(address) (external)
    - poolDelegate() (external)
    - poolDelegateCover() (external)
    - previewRedeem(address,uint256) (external)
    - previewWithdraw(address,uint256) (external)
    - processRedeem(uint256,address) (external)
    - processWithdraw(uint256,address) (external)
    - removeLoanManager(address) (external)
    - removeShares(uint256,address) (external)
    - requestRedeem(uint256,address) (external)
    - setWithdrawalManager(address) (external)
    - totalAssets() (external)
    - unrealizedLosses() (external)
    - withdrawalManager() (external)

+ Contract IWithdrawalManagerLike (Most derived contract)
  - From IWithdrawalManagerLike
    - addShares(uint256,address) (external)
    - isInExitWindow(address) (external)
    - lockedLiquidity() (external)
    - lockedShares(address) (external)
    - previewRedeem(address,uint256) (external)
    - processExit(address,uint256) (external)
    - removeShares(uint256,address) (external)

+ Contract ERC20Helper (Most derived contract)
  - From ERC20Helper
    - _call(address,bytes) (private)
    - approve(address,address,uint256) (internal)
    - transfer(address,address,uint256) (internal)
    - transferFrom(address,address,address,uint256) (internal)

+ Contract IERC20Like (Most derived contract)
  - From IERC20Like
    - approve(address,uint256) (external)
    - transfer(address,uint256) (external)
    - transferFrom(address,address,uint256) (external)

+ Contract ERC20
  - From IERC20
    - PERMIT_TYPEHASH() (external)
    - allowance(address,address) (external)
    - balanceOf(address) (external)
    - decimals() (external)
    - name() (external)
    - nonces(address) (external)
    - symbol() (external)
    - totalSupply() (external)
  - From ERC20
    - DOMAIN_SEPARATOR() (public)
    - _approve(address,address,uint256) (internal)
    - _burn(address,uint256) (internal)
    - _decreaseAllowance(address,address,uint256) (internal)
    - _mint(address,uint256) (internal)
    - _transfer(address,address,uint256) (internal)
    - approve(address,uint256) (public)
    - constructor(string,string,uint8) (public)
    - decreaseAllowance(address,uint256) (public)
    - increaseAllowance(address,uint256) (public)
    - permit(address,address,uint256,uint256,uint8,bytes32,bytes32) (public)
    - transfer(address,uint256) (public)
    - transferFrom(address,address,uint256) (public)

+ Contract IERC20
  - From IERC20
    - DOMAIN_SEPARATOR() (external)
    - PERMIT_TYPEHASH() (external)
    - allowance(address,address) (external)
    - approve(address,uint256) (external)
    - balanceOf(address) (external)
    - decimals() (external)
    - decreaseAllowance(address,uint256) (external)
    - increaseAllowance(address,uint256) (external)
    - name() (external)
    - nonces(address) (external)
    - permit(address,address,uint256,uint256,uint8,bytes32,bytes32) (external)
    - symbol() (external)
    - totalSupply() (external)
    - transfer(address,uint256) (external)
    - transferFrom(address,address,uint256) (external)

modules/pool-v2/contracts/Pool.sol analyzed (20 contracts)
