
Contract DebtLockerFactory
Contract vars: ['_implementationOf', '_versionOf', '_migratorForPath', 'mapleGlobals', 'defaultVersion', 'upgradeEnabledForPath', 'factoryType']
Inheritance:: ['MapleProxyFactory', 'ProxyFactory', 'IDebtLockerFactory', 'IMapleProxyFactory', 'IDefaultImplementationBeacon']
 
+-------------------------------------------------+------------+------------------+-------------------------------------------+-------------------------------------+-----------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                     Function                    | Visibility |    Modifiers     |                    Read                   |                Write                |                       Internal Calls                      |                                                                             External Calls                                                                             |
+-------------------------------------------------+------------+------------------+-------------------------------------------+-------------------------------------+-----------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|               constructor(address)              |   public   |        []        |              ['mapleGlobals']             |           ['mapleGlobals']          |                  ['require(bool,string)']                 |                                                     ['IMapleGlobalsLike(mapleGlobals = mapleGlobals_).governor()']                                                     |
|       disableUpgradePath(uint256,uint256)       |   public   | ['onlyGovernor'] |                     []                    |      ['upgradeEnabledForPath']      |           ['onlyGovernor', '_registerMigrator']           |                                                                                   []                                                                                   |
|                                                 |            |                  |                                           |                                     |                  ['require(bool,string)']                 |                                                                                                                                                                        |
|    enableUpgradePath(uint256,uint256,address)   |   public   | ['onlyGovernor'] |                     []                    |      ['upgradeEnabledForPath']      |           ['onlyGovernor', '_registerMigrator']           |                                                                                   []                                                                                   |
|                                                 |            |                  |                                           |                                     |                  ['require(bool,string)']                 |                                                                                                                                                                        |
| registerImplementation(uint256,address,address) |   public   | ['onlyGovernor'] |                     []                    |                  []                 |           ['onlyGovernor', '_registerMigrator']           |                                                                                   []                                                                                   |
|                                                 |            |                  |                                           |                                     |    ['require(bool,string)', '_registerImplementation']    |                                                                                                                                                                        |
|            setDefaultVersion(uint256)           |   public   | ['onlyGovernor'] |  ['_implementationOf', 'defaultVersion']  |          ['defaultVersion']         |          ['onlyGovernor', 'require(bool,string)']         |                                                                                   []                                                                                   |
|               setGlobals(address)               |   public   | ['onlyGovernor'] |              ['mapleGlobals']             |           ['mapleGlobals']          |          ['onlyGovernor', 'require(bool,string)']         |                                                            ['IMapleGlobalsLike(mapleGlobals_).governor()']                                                             |
|          createInstance(bytes,bytes32)          |   public   |        []        |             ['defaultVersion']            |                  []                 |        ['require(bool,string)', 'keccak256(bytes)']       |                                                                 ['abi.encodePacked(arguments_,salt_)']                                                                 |
|                                                 |            |                  |                                           |                                     |           ['_newInstance', 'abi.encodePacked()']          |                                                                                                                                                                        |
|          upgradeInstance(uint256,bytes)         |   public   |        []        |  ['_versionOf', 'upgradeEnabledForPath']  |                  []                 |        ['_upgradeInstance', 'require(bool,string)']       |                                                             ['IMapleProxied(msg.sender).implementation()']                                                             |
|                                                 |            |                  |               ['msg.sender']              |                                     |                                                           |                                                                                                                                                                        |
|        getInstanceAddress(bytes,bytes32)        |   public   |        []        |                     []                    |                  []                 |   ['keccak256(bytes)', '_getDeterministicProxyAddress']   |                                                                 ['abi.encodePacked(arguments_,salt_)']                                                                 |
|                                                 |            |                  |                                           |                                     |                   ['abi.encodePacked()']                  |                                                                                                                                                                        |
|            implementationOf(uint256)            |   public   |        []        |           ['_implementationOf']           |                  []                 |                             []                            |                                                                                   []                                                                                   |
|             defaultImplementation()             |  external  |        []        |  ['_implementationOf', 'defaultVersion']  |                  []                 |                             []                            |                                                                                   []                                                                                   |
|         migratorForPath(uint256,uint256)        |   public   |        []        |            ['_migratorForPath']           |                  []                 |                             []                            |                                                                                   []                                                                                   |
|                versionOf(address)               |   public   |        []        |               ['_versionOf']              |                  []                 |                             []                            |                                                                                   []                                                                                   |
|        _getImplementationOfProxy(address)       |  private   |        []        |                     []                    |                  []                 |        ['abi.decode()', 'abi.encodeWithSelector()']       |              ['proxy_.staticcall(abi.encodeWithSelector(IProxied.implementation.selector))', 'abi.encodeWithSelector(IProxied.implementation.selector)']               |
|                                                 |            |                  |                                           |                                     |                                                           |                                                                  ['abi.decode(returnData,(address))']                                                                  |
|    _initializeInstance(address,uint256,bytes)   |  private   |        []        |            ['_migratorForPath']           |                  []                 |                ['abi.encodeWithSelector()']               | ['proxy_.call(abi.encodeWithSelector(IProxied.migrate.selector,initializer,arguments_))', 'abi.encodeWithSelector(IProxied.migrate.selector,initializer,arguments_)']  |
|           _newInstance(uint256,bytes)           |  internal  |        []        |       ['_implementationOf', 'this']       |                  []                 |                  ['_initializeInstance']                  |                                                              ['new Proxy(address(this),implementation)']                                                               |
|           _newInstance(bytes,bytes32)           |  internal  |        []        |           ['_versionOf', 'this']          |                  []                 |    ['_getImplementationOfProxy', '_initializeInstance']   |                                                                ['new Proxy(address(this),address(0))']                                                                 |
|     _registerImplementation(uint256,address)    |  internal  |        []        |    ['_implementationOf', '_versionOf']    | ['_implementationOf', '_versionOf'] |                      ['_isContract']                      |                                                                                   []                                                                                   |
|    _registerMigrator(uint256,uint256,address)   |  internal  |        []        |                     []                    |         ['_migratorForPath']        |                      ['_isContract']                      |                                                                                   []                                                                                   |
|     _upgradeInstance(address,uint256,bytes)     |  internal  |        []        | ['_implementationOf', '_migratorForPath'] |                  []                 | ['_getImplementationOfProxy', 'abi.encodeWithSelector()'] | ['proxy_.call(abi.encodeWithSelector(IProxied.setImplementation.selector,toImplementation))', 'abi.encodeWithSelector(IProxied.migrate.selector,migrator,arguments_)'] |
|                                                 |            |                  |               ['_versionOf']              |                                     |                      ['_isContract']                      | ['abi.encodeWithSelector(IProxied.setImplementation.selector,toImplementation)', 'proxy_.call(abi.encodeWithSelector(IProxied.migrate.selector,migrator,arguments_))'] |
|      _getDeterministicProxyAddress(bytes32)     |  internal  |        []        |                  ['this']                 |                  []                 |            ['abi.encode()', 'keccak256(bytes)']           |                     ['abi.encodePacked(type()(Proxy).creationCode,abi.encode(address(this),address(0)))', 'abi.encode(address(this),address(0))']                      |
|                                                 |            |                  |                                           |                                     |              ['abi.encodePacked()', 'type()']             |       ['abi.encodePacked(bytes1(0xff),address(this),salt_,keccak256(bytes)(abi.encodePacked(type()(Proxy).creationCode,abi.encode(address(this),address(0)))))']       |
|               _isContract(address)              |  internal  |        []        |                     []                    |                  []                 |                     ['code(address)']                     |                                                                                   []                                                                                   |
|                 defaultVersion()                |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|                  mapleGlobals()                 |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|      upgradeEnabledForPath(uint256,uint256)     |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|          createInstance(bytes,bytes32)          |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|    enableUpgradePath(uint256,uint256,address)   |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|       disableUpgradePath(uint256,uint256)       |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
| registerImplementation(uint256,address,address) |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|            setDefaultVersion(uint256)           |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|               setGlobals(address)               |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|          upgradeInstance(uint256,bytes)         |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|        getInstanceAddress(bytes,bytes32)        |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|            implementationOf(uint256)            |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|         migratorForPath(uint256,uint256)        |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|                versionOf(address)               |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|             defaultImplementation()             |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|                  factoryType()                  |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|                newLocker(address)               |  external  |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|               constructor(address)              |   public   |        []        |                     []                    |                  []                 |                            ['']                           |                                                                                   []                                                                                   |
|                newLocker(address)               |  external  |        []        |      ['defaultVersion', 'msg.sender']     |                  []                 |              ['_newInstance', 'abi.encode()']             |                                                                    ['abi.encode(loan_,msg.sender)']                                                                    |
|                                                 |            |                  |                                           |                                     |                  ['require(bool,string)']                 |                                                                                                                                                                        |
|          createInstance(bytes,bytes32)          |   public   |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|        getInstanceAddress(bytes,bytes32)        |   public   |        []        |                     []                    |                  []                 |                             []                            |                                                                                   []                                                                                   |
|      slitherConstructorConstantVariables()      |  internal  |        []        |                     []                    |           ['factoryType']           |                             []                            |                                                                                   []                                                                                   |
+-------------------------------------------------+------------+------------------+-------------------------------------------+-------------------------------------+-----------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+----------------+------------+--------------------------------+-------+--------------------------+------------------------------------------------+
|   Modifiers    | Visibility |              Read              | Write |      Internal Calls      |                 External Calls                 |
+----------------+------------+--------------------------------+-------+--------------------------+------------------------------------------------+
| onlyGovernor() |  internal  | ['mapleGlobals', 'msg.sender'] |   []  | ['require(bool,string)'] | ['IMapleGlobalsLike(mapleGlobals).governor()'] |
+----------------+------------+--------------------------------+-------+--------------------------+------------------------------------------------+


Contract IDebtLockerFactory
Contract vars: []
Inheritance:: ['IMapleProxyFactory', 'IDefaultImplementationBeacon']
 
+-------------------------------------------------+------------+-----------+------+-------+----------------+----------------+
|                     Function                    | Visibility | Modifiers | Read | Write | Internal Calls | External Calls |
+-------------------------------------------------+------------+-----------+------+-------+----------------+----------------+
|                 defaultVersion()                |  external  |     []    |  []  |   []  |       []       |       []       |
|                  mapleGlobals()                 |  external  |     []    |  []  |   []  |       []       |       []       |
|      upgradeEnabledForPath(uint256,uint256)     |  external  |     []    |  []  |   []  |       []       |       []       |
|          createInstance(bytes,bytes32)          |  external  |     []    |  []  |   []  |       []       |       []       |
|    enableUpgradePath(uint256,uint256,address)   |  external  |     []    |  []  |   []  |       []       |       []       |
|       disableUpgradePath(uint256,uint256)       |  external  |     []    |  []  |   []  |       []       |       []       |
| registerImplementation(uint256,address,address) |  external  |     []    |  []  |   []  |       []       |       []       |
|            setDefaultVersion(uint256)           |  external  |     []    |  []  |   []  |       []       |       []       |
|               setGlobals(address)               |  external  |     []    |  []  |   []  |       []       |       []       |
|          upgradeInstance(uint256,bytes)         |  external  |     []    |  []  |   []  |       []       |       []       |
|        getInstanceAddress(bytes,bytes32)        |  external  |     []    |  []  |   []  |       []       |       []       |
|            implementationOf(uint256)            |  external  |     []    |  []  |   []  |       []       |       []       |
|         migratorForPath(uint256,uint256)        |  external  |     []    |  []  |   []  |       []       |       []       |
|                versionOf(address)               |  external  |     []    |  []  |   []  |       []       |       []       |
|             defaultImplementation()             |  external  |     []    |  []  |   []  |       []       |       []       |
|                  factoryType()                  |  external  |     []    |  []  |   []  |       []       |       []       |
|                newLocker(address)               |  external  |     []    |  []  |   []  |       []       |       []       |
+-------------------------------------------------+------------+-----------+------+-------+----------------+----------------+

+-----------+------------+------+-------+----------------+----------------+
| Modifiers | Visibility | Read | Write | Internal Calls | External Calls |
+-----------+------------+------+-------+----------------+----------------+
+-----------+------------+------+-------+----------------+----------------+


Contract MapleProxyFactory
Contract vars: ['_implementationOf', '_versionOf', '_migratorForPath', 'mapleGlobals', 'defaultVersion', 'upgradeEnabledForPath']
Inheritance:: ['ProxyFactory', 'IMapleProxyFactory', 'IDefaultImplementationBeacon']
 
+-------------------------------------------------+------------+------------------+-------------------------------------------+-------------------------------------+-------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                     Function                    | Visibility |    Modifiers     |                    Read                   |                Write                |                     Internal Calls                    |                                                                                                                  External Calls                                                                                                                 |
+-------------------------------------------------+------------+------------------+-------------------------------------------+-------------------------------------+-------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        _getImplementationOfProxy(address)       |  private   |        []        |                     []                    |                  []                 |      ['abi.decode()', 'abi.encodeWithSelector()']     |                                                               ['abi.decode(returnData,(address))', 'proxy_.staticcall(abi.encodeWithSelector(IProxied.implementation.selector))']                                                               |
|                                                 |            |                  |                                           |                                     |                                                       |                                                                                           ['abi.encodeWithSelector(IProxied.implementation.selector)']                                                                                          |
|    _initializeInstance(address,uint256,bytes)   |  private   |        []        |            ['_migratorForPath']           |                  []                 |              ['abi.encodeWithSelector()']             |                                      ['abi.encodeWithSelector(IProxied.migrate.selector,initializer,arguments_)', 'proxy_.call(abi.encodeWithSelector(IProxied.migrate.selector,initializer,arguments_))']                                      |
|           _newInstance(uint256,bytes)           |  internal  |        []        |       ['_implementationOf', 'this']       |                  []                 |                ['_initializeInstance']                |                                                                                                   ['new Proxy(address(this),implementation)']                                                                                                   |
|           _newInstance(bytes,bytes32)           |  internal  |        []        |           ['_versionOf', 'this']          |                  []                 |  ['_initializeInstance', '_getImplementationOfProxy'] |                                                                                                     ['new Proxy(address(this),address(0))']                                                                                                     |
|     _registerImplementation(uint256,address)    |  internal  |        []        |    ['_implementationOf', '_versionOf']    | ['_implementationOf', '_versionOf'] |                    ['_isContract']                    |                                                                                                                        []                                                                                                                       |
|    _registerMigrator(uint256,uint256,address)   |  internal  |        []        |                     []                    |         ['_migratorForPath']        |                    ['_isContract']                    |                                                                                                                        []                                                                                                                       |
|     _upgradeInstance(address,uint256,bytes)     |  internal  |        []        | ['_implementationOf', '_migratorForPath'] |                  []                 |      ['_isContract', 'abi.encodeWithSelector()']      |                                  ['proxy_.call(abi.encodeWithSelector(IProxied.setImplementation.selector,toImplementation))', 'abi.encodeWithSelector(IProxied.setImplementation.selector,toImplementation)']                                  |
|                                                 |            |                  |               ['_versionOf']              |                                     |             ['_getImplementationOfProxy']             |                                         ['abi.encodeWithSelector(IProxied.migrate.selector,migrator,arguments_)', 'proxy_.call(abi.encodeWithSelector(IProxied.migrate.selector,migrator,arguments_))']                                         |
|      _getDeterministicProxyAddress(bytes32)     |  internal  |        []        |                  ['this']                 |                  []                 |          ['abi.encode()', 'keccak256(bytes)']         | ['abi.encodePacked(bytes1(0xff),address(this),salt_,keccak256(bytes)(abi.encodePacked(type()(Proxy).creationCode,abi.encode(address(this),address(0)))))', 'abi.encodePacked(type()(Proxy).creationCode,abi.encode(address(this),address(0)))'] |
|                                                 |            |                  |                                           |                                     |            ['abi.encodePacked()', 'type()']           |                                                                                                     ['abi.encode(address(this),address(0))']                                                                                                    |
|               _isContract(address)              |  internal  |        []        |                     []                    |                  []                 |                   ['code(address)']                   |                                                                                                                        []                                                                                                                       |
|                 defaultVersion()                |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|                  mapleGlobals()                 |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|      upgradeEnabledForPath(uint256,uint256)     |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|          createInstance(bytes,bytes32)          |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|    enableUpgradePath(uint256,uint256,address)   |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|       disableUpgradePath(uint256,uint256)       |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
| registerImplementation(uint256,address,address) |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|            setDefaultVersion(uint256)           |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|               setGlobals(address)               |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|          upgradeInstance(uint256,bytes)         |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|        getInstanceAddress(bytes,bytes32)        |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|            implementationOf(uint256)            |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|         migratorForPath(uint256,uint256)        |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|                versionOf(address)               |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|             defaultImplementation()             |  external  |        []        |                     []                    |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|               constructor(address)              |   public   |        []        |              ['mapleGlobals']             |           ['mapleGlobals']          |                ['require(bool,string)']               |                                                                                          ['IMapleGlobalsLike(mapleGlobals = mapleGlobals_).governor()']                                                                                         |
|       disableUpgradePath(uint256,uint256)       |   public   | ['onlyGovernor'] |                     []                    |      ['upgradeEnabledForPath']      |     ['_registerMigrator', 'require(bool,string)']     |                                                                                                                        []                                                                                                                       |
|                                                 |            |                  |                                           |                                     |                    ['onlyGovernor']                   |                                                                                                                                                                                                                                                 |
|    enableUpgradePath(uint256,uint256,address)   |   public   | ['onlyGovernor'] |                     []                    |      ['upgradeEnabledForPath']      |     ['_registerMigrator', 'require(bool,string)']     |                                                                                                                        []                                                                                                                       |
|                                                 |            |                  |                                           |                                     |                    ['onlyGovernor']                   |                                                                                                                                                                                                                                                 |
| registerImplementation(uint256,address,address) |   public   | ['onlyGovernor'] |                     []                    |                  []                 |    ['_registerMigrator', '_registerImplementation']   |                                                                                                                        []                                                                                                                       |
|                                                 |            |                  |                                           |                                     |        ['require(bool,string)', 'onlyGovernor']       |                                                                                                                                                                                                                                                 |
|            setDefaultVersion(uint256)           |   public   | ['onlyGovernor'] |  ['_implementationOf', 'defaultVersion']  |          ['defaultVersion']         |        ['require(bool,string)', 'onlyGovernor']       |                                                                                                                        []                                                                                                                       |
|               setGlobals(address)               |   public   | ['onlyGovernor'] |              ['mapleGlobals']             |           ['mapleGlobals']          |        ['require(bool,string)', 'onlyGovernor']       |                                                                                                 ['IMapleGlobalsLike(mapleGlobals_).governor()']                                                                                                 |
|          createInstance(bytes,bytes32)          |   public   |        []        |             ['defaultVersion']            |                  []                 |          ['_newInstance', 'keccak256(bytes)']         |                                                                                                      ['abi.encodePacked(arguments_,salt_)']                                                                                                     |
|                                                 |            |                  |                                           |                                     |     ['require(bool,string)', 'abi.encodePacked()']    |                                                                                                                                                                                                                                                 |
|          upgradeInstance(uint256,bytes)         |   public   |        []        |  ['_versionOf', 'upgradeEnabledForPath']  |                  []                 |      ['require(bool,string)', '_upgradeInstance']     |                                                                                                  ['IMapleProxied(msg.sender).implementation()']                                                                                                 |
|                                                 |            |                  |               ['msg.sender']              |                                     |                                                       |                                                                                                                                                                                                                                                 |
|        getInstanceAddress(bytes,bytes32)        |   public   |        []        |                     []                    |                  []                 | ['_getDeterministicProxyAddress', 'keccak256(bytes)'] |                                                                                                      ['abi.encodePacked(arguments_,salt_)']                                                                                                     |
|                                                 |            |                  |                                           |                                     |                 ['abi.encodePacked()']                |                                                                                                                                                                                                                                                 |
|            implementationOf(uint256)            |   public   |        []        |           ['_implementationOf']           |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|             defaultImplementation()             |  external  |        []        |  ['_implementationOf', 'defaultVersion']  |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|         migratorForPath(uint256,uint256)        |   public   |        []        |            ['_migratorForPath']           |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
|                versionOf(address)               |   public   |        []        |               ['_versionOf']              |                  []                 |                           []                          |                                                                                                                        []                                                                                                                       |
+-------------------------------------------------+------------+------------------+-------------------------------------------+-------------------------------------+-------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+----------------+------------+--------------------------------+-------+--------------------------+------------------------------------------------+
|   Modifiers    | Visibility |              Read              | Write |      Internal Calls      |                 External Calls                 |
+----------------+------------+--------------------------------+-------+--------------------------+------------------------------------------------+
| onlyGovernor() |  internal  | ['mapleGlobals', 'msg.sender'] |   []  | ['require(bool,string)'] | ['IMapleGlobalsLike(mapleGlobals).governor()'] |
+----------------+------------+--------------------------------+-------+--------------------------+------------------------------------------------+


Contract IMapleProxied
Contract vars: []
Inheritance:: ['IProxied']
 
+----------------------------+------------+-----------+------+-------+----------------+----------------+
|          Function          | Visibility | Modifiers | Read | Write | Internal Calls | External Calls |
+----------------------------+------------+-----------+------+-------+----------------+----------------+
|         factory()          |  external  |     []    |  []  |   []  |       []       |       []       |
|      implementation()      |  external  |     []    |  []  |   []  |       []       |       []       |
| setImplementation(address) |  external  |     []    |  []  |   []  |       []       |       []       |
|   migrate(address,bytes)   |  external  |     []    |  []  |   []  |       []       |       []       |
|   upgrade(uint256,bytes)   |  external  |     []    |  []  |   []  |       []       |       []       |
+----------------------------+------------+-----------+------+-------+----------------+----------------+

+-----------+------------+------+-------+----------------+----------------+
| Modifiers | Visibility | Read | Write | Internal Calls | External Calls |
+-----------+------------+------+-------+----------------+----------------+
+-----------+------------+------+-------+----------------+----------------+


Contract IMapleProxyFactory
Contract vars: []
Inheritance:: ['IDefaultImplementationBeacon']
 
+-------------------------------------------------+------------+-----------+------+-------+----------------+----------------+
|                     Function                    | Visibility | Modifiers | Read | Write | Internal Calls | External Calls |
+-------------------------------------------------+------------+-----------+------+-------+----------------+----------------+
|             defaultImplementation()             |  external  |     []    |  []  |   []  |       []       |       []       |
|                 defaultVersion()                |  external  |     []    |  []  |   []  |       []       |       []       |
|                  mapleGlobals()                 |  external  |     []    |  []  |   []  |       []       |       []       |
|      upgradeEnabledForPath(uint256,uint256)     |  external  |     []    |  []  |   []  |       []       |       []       |
|          createInstance(bytes,bytes32)          |  external  |     []    |  []  |   []  |       []       |       []       |
|    enableUpgradePath(uint256,uint256,address)   |  external  |     []    |  []  |   []  |       []       |       []       |
|       disableUpgradePath(uint256,uint256)       |  external  |     []    |  []  |   []  |       []       |       []       |
| registerImplementation(uint256,address,address) |  external  |     []    |  []  |   []  |       []       |       []       |
|            setDefaultVersion(uint256)           |  external  |     []    |  []  |   []  |       []       |       []       |
|               setGlobals(address)               |  external  |     []    |  []  |   []  |       []       |       []       |
|          upgradeInstance(uint256,bytes)         |  external  |     []    |  []  |   []  |       []       |       []       |
|        getInstanceAddress(bytes,bytes32)        |  external  |     []    |  []  |   []  |       []       |       []       |
|            implementationOf(uint256)            |  external  |     []    |  []  |   []  |       []       |       []       |
|         migratorForPath(uint256,uint256)        |  external  |     []    |  []  |   []  |       []       |       []       |
|                versionOf(address)               |  external  |     []    |  []  |   []  |       []       |       []       |
+-------------------------------------------------+------------+-----------+------+-------+----------------+----------------+

+-----------+------------+------+-------+----------------+----------------+
| Modifiers | Visibility | Read | Write | Internal Calls | External Calls |
+-----------+------------+------+-------+----------------+----------------+
+-----------+------------+------+-------+----------------+----------------+


Contract IMapleGlobalsLike
Contract vars: []
Inheritance:: []
 
+------------+------------+-----------+------+-------+----------------+----------------+
|  Function  | Visibility | Modifiers | Read | Write | Internal Calls | External Calls |
+------------+------------+-----------+------+-------+----------------+----------------+
| governor() |  external  |     []    |  []  |   []  |       []       |       []       |
+------------+------------+-----------+------+-------+----------------+----------------+

+-----------+------------+------+-------+----------------+----------------+
| Modifiers | Visibility | Read | Write | Internal Calls | External Calls |
+-----------+------------+------+-------+----------------+----------------+
+-----------+------------+------+-------+----------------+----------------+


Contract Proxy
Contract vars: ['FACTORY_SLOT', 'IMPLEMENTATION_SLOT']
Inheritance:: ['SlotManipulatable']
 
+----------------------------------------+------------+-----------+-----------------------------------------+-----------------------------------------+----------------------------------------------------------------------------------------------+--------------------------------------------------------------------+
|                Function                | Visibility | Modifiers |                   Read                  |                  Write                  |                                        Internal Calls                                        |                           External Calls                           |
+----------------------------------------+------------+-----------+-----------------------------------------+-----------------------------------------+----------------------------------------------------------------------------------------------+--------------------------------------------------------------------+
| _getReferenceTypeSlot(bytes32,bytes32) |  internal  |     []    |                    []                   |                    []                   |                          ['keccak256(bytes)', 'abi.encodePacked()']                          |                  ['abi.encodePacked(key_,slot_)']                  |
|         _getSlotValue(bytes32)         |  internal  |     []    |                    []                   |                    []                   |                                      ['sload(uint256)']                                      |                                 []                                 |
|     _setSlotValue(bytes32,bytes32)     |  internal  |     []    |                    []                   |                    []                   |                                 ['sstore(uint256,uint256)']                                  |                                 []                                 |
|      constructor(address,address)      |   public   |     []    | ['FACTORY_SLOT', 'IMPLEMENTATION_SLOT'] |                    []                   |                              ['_setSlotValue', 'require(bool)']                              | ['IDefaultImplementationBeacon(factory_).defaultImplementation()'] |
|               fallback()               |  external  |     []    |         ['IMPLEMENTATION_SLOT']         |                    []                   |                                 ['gas()', 'calldatasize()']                                  |                                 []                                 |
|                                        |            |           |                                         |                                         | ['delegatecall(uint256,uint256,uint256,uint256,uint256,uint256)', 'revert(uint256,uint256)'] |                                                                    |
|                                        |            |           |                                         |                                         |                            ['returndatasize()', 'require(bool)']                             |                                                                    |
|                                        |            |           |                                         |                                         |                 ['_getSlotValue', 'returndatacopy(uint256,uint256,uint256)']                 |                                                                    |
|                                        |            |           |                                         |                                         |                  ['code(address)', 'calldatacopy(uint256,uint256,uint256)']                  |                                                                    |
|                                        |            |           |                                         |                                         |                                 ['return(uint256,uint256)']                                  |                                                                    |
| slitherConstructorConstantVariables()  |  internal  |     []    |                    []                   | ['FACTORY_SLOT', 'IMPLEMENTATION_SLOT'] |                                              []                                              |                                 []                                 |
+----------------------------------------+------------+-----------+-----------------------------------------+-----------------------------------------+----------------------------------------------------------------------------------------------+--------------------------------------------------------------------+

+-----------+------------+------+-------+----------------+----------------+
| Modifiers | Visibility | Read | Write | Internal Calls | External Calls |
+-----------+------------+------+-------+----------------+----------------+
+-----------+------------+------+-------+----------------+----------------+


Contract ProxyFactory
Contract vars: ['_implementationOf', '_versionOf', '_migratorForPath']
Inheritance:: []
 
+--------------------------------------------+------------+-----------+-------------------------------------------+-------------------------------------+-----------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                  Function                  | Visibility | Modifiers |                    Read                   |                Write                |                       Internal Calls                      |                                                                                           External Calls                                                                                           |
+--------------------------------------------+------------+-----------+-------------------------------------------+-------------------------------------+-----------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|     _getImplementationOfProxy(address)     |  private   |     []    |                     []                    |                  []                 |        ['abi.decode()', 'abi.encodeWithSelector()']       |                            ['proxy_.staticcall(abi.encodeWithSelector(IProxied.implementation.selector))', 'abi.encodeWithSelector(IProxied.implementation.selector)']                             |
|                                            |            |           |                                           |                                     |                                                           |                                                                                ['abi.decode(returnData,(address))']                                                                                |
| _initializeInstance(address,uint256,bytes) |  private   |     []    |            ['_migratorForPath']           |                  []                 |                ['abi.encodeWithSelector()']               |               ['abi.encodeWithSelector(IProxied.migrate.selector,initializer,arguments_)', 'proxy_.call(abi.encodeWithSelector(IProxied.migrate.selector,initializer,arguments_))']                |
|        _newInstance(uint256,bytes)         |  internal  |     []    |       ['_implementationOf', 'this']       |                  []                 |                  ['_initializeInstance']                  |                                                                            ['new Proxy(address(this),implementation)']                                                                             |
|        _newInstance(bytes,bytes32)         |  internal  |     []    |           ['_versionOf', 'this']          |                  []                 |    ['_initializeInstance', '_getImplementationOfProxy']   |                                                                              ['new Proxy(address(this),address(0))']                                                                               |
|  _registerImplementation(uint256,address)  |  internal  |     []    |    ['_implementationOf', '_versionOf']    | ['_implementationOf', '_versionOf'] |                      ['_isContract']                      |                                                                                                 []                                                                                                 |
| _registerMigrator(uint256,uint256,address) |  internal  |     []    |                     []                    |         ['_migratorForPath']        |                      ['_isContract']                      |                                                                                                 []                                                                                                 |
|  _upgradeInstance(address,uint256,bytes)   |  internal  |     []    | ['_implementationOf', '_migratorForPath'] |                  []                 | ['abi.encodeWithSelector()', '_getImplementationOfProxy'] |                  ['proxy_.call(abi.encodeWithSelector(IProxied.migrate.selector,migrator,arguments_))', 'abi.encodeWithSelector(IProxied.migrate.selector,migrator,arguments_)']                   |
|                                            |            |           |               ['_versionOf']              |                                     |                      ['_isContract']                      |           ['abi.encodeWithSelector(IProxied.setImplementation.selector,toImplementation)', 'proxy_.call(abi.encodeWithSelector(IProxied.setImplementation.selector,toImplementation))']            |
|   _getDeterministicProxyAddress(bytes32)   |  internal  |     []    |                  ['this']                 |                  []                 |            ['abi.encode()', 'keccak256(bytes)']           | ['abi.encodePacked(bytes1(0xff),address(this),salt_,keccak256(bytes)(abi.encodePacked(type()(Proxy).creationCode,abi.encode(address(this),address(0)))))', 'abi.encode(address(this),address(0))'] |
|                                            |            |           |                                           |                                     |              ['abi.encodePacked()', 'type()']             |                                                       ['abi.encodePacked(type()(Proxy).creationCode,abi.encode(address(this),address(0)))']                                                        |
|            _isContract(address)            |  internal  |     []    |                     []                    |                  []                 |                     ['code(address)']                     |                                                                                                 []                                                                                                 |
+--------------------------------------------+------------+-----------+-------------------------------------------+-------------------------------------+-----------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+-----------+------------+------+-------+----------------+----------------+
| Modifiers | Visibility | Read | Write | Internal Calls | External Calls |
+-----------+------------+------+-------+----------------+----------------+
+-----------+------------+------+-------+----------------+----------------+


Contract SlotManipulatable
Contract vars: []
Inheritance:: []
 
+----------------------------------------+------------+-----------+------+-------+--------------------------------------------+----------------------------------+
|                Function                | Visibility | Modifiers | Read | Write |               Internal Calls               |          External Calls          |
+----------------------------------------+------------+-----------+------+-------+--------------------------------------------+----------------------------------+
| _getReferenceTypeSlot(bytes32,bytes32) |  internal  |     []    |  []  |   []  | ['keccak256(bytes)', 'abi.encodePacked()'] | ['abi.encodePacked(key_,slot_)'] |
|         _getSlotValue(bytes32)         |  internal  |     []    |  []  |   []  |             ['sload(uint256)']             |                []                |
|     _setSlotValue(bytes32,bytes32)     |  internal  |     []    |  []  |   []  |        ['sstore(uint256,uint256)']         |                []                |
+----------------------------------------+------------+-----------+------+-------+--------------------------------------------+----------------------------------+

+-----------+------------+------+-------+----------------+----------------+
| Modifiers | Visibility | Read | Write | Internal Calls | External Calls |
+-----------+------------+------+-------+----------------+----------------+
+-----------+------------+------+-------+----------------+----------------+


Contract IDefaultImplementationBeacon
Contract vars: []
Inheritance:: []
 
+-------------------------+------------+-----------+------+-------+----------------+----------------+
|         Function        | Visibility | Modifiers | Read | Write | Internal Calls | External Calls |
+-------------------------+------------+-----------+------+-------+----------------+----------------+
| defaultImplementation() |  external  |     []    |  []  |   []  |       []       |       []       |
+-------------------------+------------+-----------+------+-------+----------------+----------------+

+-----------+------------+------+-------+----------------+----------------+
| Modifiers | Visibility | Read | Write | Internal Calls | External Calls |
+-----------+------------+------+-------+----------------+----------------+
+-----------+------------+------+-------+----------------+----------------+


Contract IProxied
Contract vars: []
Inheritance:: []
 
+----------------------------+------------+-----------+------+-------+----------------+----------------+
|          Function          | Visibility | Modifiers | Read | Write | Internal Calls | External Calls |
+----------------------------+------------+-----------+------+-------+----------------+----------------+
|         factory()          |  external  |     []    |  []  |   []  |       []       |       []       |
|      implementation()      |  external  |     []    |  []  |   []  |       []       |       []       |
| setImplementation(address) |  external  |     []    |  []  |   []  |       []       |       []       |
|   migrate(address,bytes)   |  external  |     []    |  []  |   []  |       []       |       []       |
+----------------------------+------------+-----------+------+-------+----------------+----------------+

+-----------+------------+------+-------+----------------+----------------+
| Modifiers | Visibility | Read | Write | Internal Calls | External Calls |
+-----------+------------+------+-------+----------------+----------------+
+-----------+------------+------+-------+----------------+----------------+

modules/debt-locker-v4/contracts/DebtLockerFactory.sol analyzed (11 contracts)
