name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
  ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}

  FOUNDRY_PROFILE: ${{ github.event_name == 'push' && 'production' || 'default' }}
  FUZZ_PROFILE: ${{ github.event_name == 'push' && 'super_deep' || 'deep' }}

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Update submodules
        run: ./setup-ci.sh
      - name: Run integration tests
        run: ./test.sh -d tests/integration -p $FOUNDRY_PROFILE

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Update submodules
        run: ./setup-ci.sh
      - name: Run end to end tests
        run: ./test.sh -d tests/e2e -p $FOUNDRY_PROFILE

  fuzz-tests:
    runs-on:
      group: SC-HighMemory
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Update submodules
        run: ./setup-ci.sh
      - name: Run fuzz tests
        run: ./test.sh -t testFuzz -p $FUZZ_PROFILE

  invariant-tests:
    runs-on:
        group: SC-HighMemory
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Update submodules
        run: ./setup-ci.sh
      - name: Run invariant tests
        run: ./test.sh -d tests/invariants -p $FUZZ_PROFILE

  scenario-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "nightly-0dceb536da7129c8e58b2c30c7059e247467838f"
      - name: Install Node
        uses: actions/setup-node@v4
      - name: Update submodules
        run: ./setup-ci.sh
      - name: Run Scenarios
        run: ./scenarios.sh

  protocol-upgrade-tests:
    runs-on:
        group: SC-HighMemory
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Update submodules
        run: ./setup-ci.sh
      - name: Run Protocol Upgrade tests
        run: ./test.sh -d tests/protocol-upgrade -p $FOUNDRY_PROFILE
