name: Forge Tests (PR)

on: [pull_request]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        shell: bash
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
          BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
        run: make e2e profile=production

  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        shell: bash
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
          BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
        run: make integration profile=production

  fuzz_tests:
    runs-on:
        group: SC-HighMemory
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        shell: bash
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
          BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
        run: ./test.sh -p deep -t testFuzz

  invariant_tests:
    runs-on:
        group: SC-HighMemory
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        shell: bash
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
          BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
        run: make invariant profile=deep

  protocol-upgrade:
    runs-on:
        group: SC-HighMemory
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        shell: bash
        run: |
          chmod +x ./setup-ci.sh
          ./setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
          BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
        run: make protocol-upgrade

  scenario_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - uses: actions/setup-node@v3

      - name: Checkout submodules
        shell: bash
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
          BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
        run: make scenario
