name: Forge Tests (PR)

on: [pull_request]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./setup-ci.sh
          ./setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make e2e profile=production

  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./setup-ci.sh
          ./setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make integration profile=production

  deep_fuzz_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./setup-ci.sh
          ./setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: ./test.sh -p deep -t testDeepFuzz_

  shallow_fuzz_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./setup-ci.sh
          ./setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: ./test.sh -p shallow -t testShallowFuzz_

  invariant_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./setup-ci.sh
          ./setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make invariant profile=deep

  local_simulations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./setup-ci.sh
          ./setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make local-sim

  mainnet_simulations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Cache RPC Responses"
        uses: "actions/cache@v3"
        with:
          path: "~/.foundry/cache/rpc/mainnet/16156537"
          key: "${{ runner.os }}-mainnet-16156537"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./setup-ci.sh
          ./setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make mainnet-sim

