name: Forge Tests (PR)

on: [pull_request]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make e2e profile=production

  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make integration profile=production

  fuzz_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: ./test.sh -p deep -t Fuzz

  invariant_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make invariant profile=deep

  scenario_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - uses: actions/setup-node@v3

      - name: Checkout submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make scenario

  upgrade_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Cache RPC Responses"
        uses: "actions/cache@v3"
        with:
          path: "~/.foundry/cache/rpc/mainnet/16990500"
          key: "${{ runner.os }}-mainnet-16990500"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Checkout submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: make upgrade profile=production
